# Generated by Django 4.2.7 on 2024-01-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_recipient_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_account',
        ),
    ]
